apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: hello-world
